### PR TITLE
unicode_names2_generator as build dependency

### PR DESCRIPTION
**Pull request by youknowone**
Because generator is now deterministic, we can use it as build dependency.

And finally formatting and CI for formatting

closes #16
closes #15

### CODE REVIEW

**Comment by progval** [comment]
Not that I'm against this change, but what does non-determinism have to do with being used as a build-dep?

**Comment by youknowone** [comment]
No problem if everything is perfect.
But suppose we have glitch on hash or random function at edge case. With deterministic build, the full database can be tested and it guarantees the generated code doesn't have bug even if there is bug on hash or random.
With non-deterministic build, users randomly will get bugs by each build time in rare chance.

**Comment by progval** [comment]
it looks like you ran `rustfmt` in addition to your changes in the `unicode_names2_generator as build dependency` commit. Could you insert a commit with only the `rustfmt` changes before that commit, so the commit can be read more easily?

**Comment by progval** [comment]
thanks

**Pull request merged**
