### PR TITLE
Update to Unicode 12

### PR DESCRIPTION
**Pull request by antifuchs**
It's a new Unicode release (this one includes the Lobster emoji)! Time to:

* Pull in the newest UnicodeData.txt
* Re-run the generator

(-:

### CODE REVIEW

**Comment by antifuchs** [comment]
I tried to run the tests, but these fail on nightly these days. Maybe stable proc macros broke the macro crate.

**Comment by progval** [comment]
I fixed master, thanks for noticing it. Now you have an actual test failure! :D

**Comment by antifuchs** [comment]
Oopsie! I forgot to run the generator in PHF mode, too. To counteract this, I added a `make generate` task that should ensure we correctly update the code when we update the data files.

**Comment by antifuchs** [comment]
An open question, as always, is what parameters to use on the PHF. I tried the benchmarks on some alterations to the defaults, but straying from the default values resulted in ~no changes in performance.

**Comment by progval** [comment]
>  I added a `make generate` task that should ensure we correctly update the code when we update the data files.

Thanks!

> An open question, as always, is what parameters to use on the PHF.

I don't know. To be honest, I never heard of PHFs before today... We could take a look at what other unicode libraries do, if any of them uses PHFs too.

**Comment by antifuchs** [comment]
Thanks you for getting this merged so quickly! I think the only real difference we could get out of the perfect hash is maybe size - it might be interesting to experiment with it and see how large release binaries get with the different parameters.

One other request: Can you cut a crates.io release? I would love to use Unicode 12 in `chars` (:

Update: saw your other PR, doing that first sounds good (-:

**Comment by progval** [comment]
> One other request: Can you cut a crates.io release? I would love to use Unicode 12 in `chars` (:

Sure. There's no backward incompatibility when upgrading unicode versions, right?

**Comment by antifuchs** [comment]
There may have been renames of characters, so I think marking it as non-backwards compat is quite reasonable!

**Pull request merged**
