### PR TITLE
Bump time dependency to 0.3

### PR DESCRIPTION
**Pull request by jelmer**
Bump time dependency to 0.3

### CODE REVIEW

**Comment by progval** [comment]
Could you add this to `.github/workflows/ci.yml` in order to fix the build on Rust 1.63.0?

```yaml
      - name: downgrade 'time' for Rust 1.63.0
        uses: actions-rs/cargo@v1
        with:
          command: update
          args: --package time --precise 0.3.20
        if: ${{ matrix.features == '1.63.0' }}
```

as a workaround for https://github.com/rust-lang/cargo/issues/9930

(not tested)

**Comment by jelmer** [comment]
makes sense; done

**Comment by progval** [comment]
Thanks again! I'll push a release in a bit

**Comment by progval** [comment]
Done!

**Pull request merged**
