### PR TITLE
include required license texts in all published crates

### PR DESCRIPTION
**Pull request by decathorpe**
For context: I'm in the process of packaging the crates from this project for Fedora Linux as a dependency of "ruff" (the fancy new Python linter + formatter).

I noticed that the `unicode_names2` crate contains some Unicode data files (under `data/`), which is explicitly covered by the Unicode "Data Files and Software" license, but the text for that license is not included, and the crate metadata does not reflect this fact either.

For example, the widely-used `unicode-ident` crate is in a similar situation, and it includes the Unicode license text, and lists the Unicode license in its crate metadata: <https://github.com/dtolnay/unicode-ident>

---

With this PR, I've attempted to "fix" some issues regarding this project's license specification / texts, some of which currently would prevent it from being packaged for Fedora Linux:

- include text for the Unicode license (up-to-date version from <https://www.unicode.org/license.txt>)
- include `Unicode-DFS-2016` in the license for the `unicode_names2` crate (`Unicode-DFS-2016` is the SPDX identifier for this license text, see <https://spdx.org/licenses/Unicode-DFS-2016.html>)
- ensure that the license files for the Apache-2.0 and MIT licenses are included when publishing *all* crates from this project (if you are running "cargo publish" in Windows, the symbolic links might not be enough here, though)
- update SPDX license expressions to replace the deprecated `/` syntax with `OR`

---

If this PR is acceptable, it would be great if you could publish a new version with these changes to crates.io. Thank you!

### CODE REVIEW

**Comment by progval** [comment]
Thanks. Could you just move `LICENSE-UNICODE` to the `data/` subdirectory to make it clear it only applies to files in that directory?

**Comment by decathorpe** [comment]
> Thanks. Could you just move `LICENSE-UNICODE` to the `data/` subdirectory to make it clear it only applies to files in that directory?

Thanks for taking a look! The Unicode "Data Files and Software" license applies to the data files themselves **and** any code that is generated from them, which usually means that it applies to code as well, which is why I originally put it at the "project root". However, looking more closely, the crate does not actually ship any generated code, but it is generated on-the-fly by the build script - so the license indeed only applies to the data files. I've pushed an amended commit that moves the file into the "data/" directory.

**Comment by progval** [comment]
Thanks!

**Comment by progval** [comment]
v1.2.1 published

**Comment by decathorpe** [comment]
Awesome, thank you! 🎉

**Pull request merged**
