### PR TITLE
Update data for Unicode 13.0.0

### PR DESCRIPTION
**Pull request by antifuchs**
This PR updates the unicode data for version 13.0.0, and updates the generated files.

It's fairly straightforward, but includes one adjustment for tests: The changed assertion was invalidated by Unicode 13, as CJK unified ideograph section B now spans to `2A6DD`, and the assertion was hitting exactly the middle of the extension of the range.

### CODE REVIEW

**Comment by antifuchs** [comment]
(If you merge it, please cut a release also! I'd like to include this in a new release of `chars`)

**Comment by antifuchs** [comment]
Ugh, the test failure is from `getopt` in the generator. Bumped to 0.2.21.

**Comment by antifuchs** [comment]
(Separately, since I'll baaasically have to send the same PR every time, it would be really cool if we could break the compiled-in data out from the looking-up part into multiple crates... Let me pass in my own `'static` name tries, generated from the same data files; ideally, I'd like to break the PHF-based name->char lookup out into its own crate too, as my program has no use for that data (:)

**Comment by progval** [comment]
Thanks!

I don't fully understand what you said in your last comment; but you know this crate better than I do, so I'll trust you if you want to do this

**Comment by antifuchs** [comment]
Ah! I meant that we could break the crate apart so that users could:
* skip the features / data they don't need (e.g. lookup-by-name or name-from-character), and
* provide data they have

That would mean breaking this crate into multiple components & make it a bit more unwieldy to maintain, I imagine:

* A crate containing the generator as a library for integration in build processes: read a version of UnicodeData.txt and output the character name compressed trie & the name-lookup hashtable
* Two crates, each containing the generated data for each version (compressed trie & name-lookup)
* One containing the `unicode_names2::character` implementation
* One containing the `unicode_names2::name` implementation
* and the original `unicode_names2` crate, which pulls in all these crates and re-exports the `character`  and `name` functions

That would be a loooot of maintenance overhead; I feel that splitting the trie / name-lookup parts out might be beneficial though (:

**Comment by progval** [comment]
Sounds good!

There are already two crates depending on each other, which requires a lot of manual fiddling on every release. This split would solve this issue

**Pull request merged**
